import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'getting-started/index',
    'theming/index',
    'rtl/index',
    'tokens/index',
    {
      type: 'category',
      label: 'Components',
      link: { type: 'generated-index', title: 'Components' },
      items: [{ type: 'autogenerated', dirName: 'components' }],
    },
  ],
};

export default sidebars;
